# Generated by Django 2.1.3 on 2018-11-28 17:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscription_types', models.CharField(max_length=120)),
                ('subscription_price', models.IntegerField()),
                ('duration', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='UserMembership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=10)),
                ('active', models.BooleanField(default=False)),
                ('subscription_date', models.DateTimeField(blank=True, null=True)),
                ('exp_date', models.DateTimeField(blank=True, null=True)),
                ('subscription_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='makers_home_app.Subscription')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
